### ISSUE TITLE
Logs-folder not found

### ISSUE THREAD

**Issue by spoetnik** [tkjone/starterkit-wagtail#5]
Using the Docker branch, during initial migrate I get the error:
`    FileNotFoundError: [Errno 2] No such file or directory: '/Users/myname/Projects/projectnamelogs/django.log'`

Changing the src/config/settings/base.py line 208.
from 
`    LOG_DIR = env("LOG_DIR", default=str(ROOT_DIR) + 'logs/')`
to
`    LOG_DIR = env("LOG_DIR", default=str(ROOT_DIR) + '/logs/')
`
Works for me.....

**Comment by tkjone** [comment]
Thanks, @spoetnik - You are very right.  Resolved.

https://github.com/tkjone/starterkit-wagtail/commit/737dc6f012f0850cbd56ee516a4976ac294e85a9
